language: python
python:
  - 2.6
  - 2.7
  - 3.2

install:
  - python setup.py develop

script: python setup.py test --allow-hosts='pypi.python.org'

notifications:
  irc: "irc.freenode.org#ptahproject"
