language: python
python:
  - 2.6
  - 2.7
  - 3.2
install:
  - pip install git+git://github.com/fafhrd91/pyramid_amdjs.git
  - pip install http://gevent.googlecode.com/files/gevent-1.0b3.tar.gz
  - python setup.py develop
script: python setup.py test
notifications:
  irc: "irc.freenode.org#ptahproject"
